development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: sht_development
  pool: 5
  username: thais
  password: 744093
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: sht_test
  pool: 5
  username: thais
  password: 744093
production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: sht_production
  pool: 5
  username: thais
  password: 744093
